#!/usr/bin/env bash

set -e -x

source ~/.bashrc

# because our pipeline image adds ruby to the PATH via the bashrc, we have to
# source it.  concourse does not source it when running a build.  so we start
# as a bash script and use exec to replace the bash process with a ruby process

exec /usr/bin/env ruby -x "$0" $*
#!ruby

require 'open-uri'
require 'json'

response = open('https://canibump.cfapps.io/', 'Accept' => 'application/json').read
if JSON.parse(response)['can_i_bump']
  exit 0
else
  puts "\n\n'Can I bump' cf-release status is: No (Red)\nAborting the job..."
  exit 1
end
