#!/bin/bash

source ~/.bashrc

set -eux -o pipefail
mv cf-manifest/deployment.yml cf-manifest/cf.yml

pushd cf-mysql-release
  ./scripts/generate-deployment-manifest \
    -c ../cf-manifest/cf.yml \
    -i "../capi-ci/${ENV}/stubs/mysql/iaas-settings.yml" \
    -p "../capi-ci-private/${ENV}/stubs/mysql/property-overrides.yml" \
    -n "./manifest-generation/examples/standalone/instance-count-overrides.yml" \
    -j "../capi-ci/${ENV}/stubs/mysql/job-overrides.yml" \
    > deployment.yml
  cp deployment.yml ../generated-manifest/deployment.yml
popd
