#!/bin/bash

source ~/.bashrc

set -eux -o pipefail

bosh target ${BOSH_DIRECTOR}
bosh login ${BOSH_USER} ${BOSH_PASSWORD}
bosh download manifest cf-${ENV} generated-manifest/cf.yml

pushd cf-mysql-release
  ./scripts/generate-deployment-manifest \
    -c ../generated-manifest/cf.yml \
    -i "../capi-ci/${ENV}/stubs/mysql/iaas-settings.yml" \
    -p "../capi-ci-private/${ENV}/stubs/mysql/property-overrides.yml" \
    -n "./manifest-generation/examples/standalone/instance-count-overrides.yml" \
    > deployment.yml
  cp deployment.yml ../generated-manifest/deployment.yml
popd
