#!/usr/bin/env bash

set -exu

function setup_env() {
  export AWS_DEFAULT_REGION
  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY
}

function create_stack() {
  declare stack_name=$1 cf_path=$2

  aws cloudformation create-stack --stack-name "${stack_name}" \
    --template-body "$(cat "${cf_path}")"
}

function exit_if_stack_exists() {
  declare stack_name=$1

  set +ex
  aws cloudformation describe-stacks --stack-name "${stack_name}" 2>/dev/null
  if [ $? -eq 0 ]; then
    echo "Stack ${stack_name} already exists, bailing out"
    exit 0
  fi
  set -ex
}

function wait_for_stack() {
  declare stack_name=$1 timeout=$2

  set +x
  iterations=0

  until check_stack "${stack_name}" | grep -q CREATE_COMPLETE ; do
    iterations=$((iterations+1))
    if [ $iterations -gt $timeout ];then
      echo "Timed out waiting for stack to create" >&2
      exit 1
    fi
    echo -n . >&2
    sleep 1
  done
  set -x
}

function check_stack() {
  local stack_name=$1

  aws cloudformation describe-stacks --stack-name "${stack_name}"
}

function main() {
  local stack_id

  setup_env
  exit_if_stack_exists "${STACK_NAME}"
  create_stack "${STACK_NAME}" "${CLOUDFORMATION_PATH}"
  wait_for_stack "${STACK_NAME}" 120
}

main
