#!/usr/bin/env bash

set -exu

function setup_env() {
  export AWS_DEFAULT_REGION
  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY
}

function find_instance_id() {
  declare instance_name=$1

  aws ec2 describe-instances --filters "Name=tag:Name,Values=${instance_name}" 'Name=instance-state-name,Values=running' \
      --output text --query 'Reservations[*].Instances[*].InstanceId' \
      | tr -d "\n"
}

function deprovision_bosh_lite() {
  declare instance_id=$1

  aws ec2 terminate-instances --instance-ids "${instance_id}"
}

function wait_for_deprovisioning() {
  declare instance_id=$1

  aws ec2 wait instance-terminated --instance-ids "${instance_id}"
}

function main() {
  setup_env

  local instance_id="$(find_instance_id "${BOSH_LITE_NAME}")"

  if [ -z ${instance_id} ]; then
    echo "No instance found"
    exit 0
  fi

  deprovision_bosh_lite "${instance_id}"
  wait_for_deprovisioning "${instance_id}"
}

main
