#!/usr/bin/env bash

set -exu

FINAL_RELEASE_VERSION=$(cat version/version)
DEV_RELEASE_TARBALL=$(ls ${PWD}/capi-release-tarball/*.tgz)

RELEASE_YML="releases/capi-release-final/capi-release-final-${FINAL_RELEASE_VERSION}.yml"
RELEASE_TGZ="releases/capi-release-final/capi-release-final-${FINAL_RELEASE_VERSION}.tgz"

function setup_git_user() {
  pushd capi-release
    git config user.name 'CAPI CI'
    git config user.email cf-capi-eng+ci@pivotal.io
  popd
}

function copy_private_yml() {
  cp ${PWD}/capi-ci-private/ci/private.yml ${PWD}/capi-release/config/private.yml
}

function create_release() {
  pushd capi-release
    /opt/rubies/ruby-2.2.4/bin/bosh -n finalize release "${DEV_RELEASE_TARBALL}" --name capi-release-final --version "${FINAL_RELEASE_VERSION}"
    mv "${RELEASE_TGZ}" "../finalized-release/capi-${FINAL_RELEASE_VERSION}.tgz"

    git add -A
    git commit -m "Create final release ${FINAL_RELEASE_VERSION}"
  popd
}

function export_release() {
  cp -a capi-release finalized-release/
}

function main() {
  setup_git_user
  copy_private_yml
  create_release
  export_release
}

main
