#!/usr/bin/env bash

set -exu

function generate_cf_manifest() {
  declare stub=$1 environment_stub=$2 generated_manifest=$3

  cf-release/scripts/generate_deployment_manifest \
    bosh-lite  \
    "${stub}" \
    "${environment_stub}" > "${generated_manifest}"
}

function generate_diego_manifest() {
  declare manifest_dir=$1

  CF_MANIFESTS_DIR="$1"
  DIEGO_MANIFESTS_DIR="$1"

  pushd diego-release >/dev/null
    ./scripts/generate-bosh-lite-manifests
  popd > /dev/null
}

function main() {
  generate_cf_manifest "${STUBS_PATH}" "${ENVIRONMENT_STUB}" "generated-manifests/cf.yml"
  cat "generated-manifests/cf.yml"

  generate_diego_manifest "${PWD}/generated-manifests"
  cat "generated-manifests/diego.yml"
}

main
