#!/usr/bin/env bash

set -exu

( cd capi-release && git rev-parse HEAD ) > capi-final-releases/commitish

VERSION=$(git describe --abbrev=0 --tags)

echo "CAPI v${VERSION}" > capi-final-releases/name
echo "v${VERSION}" > capi-final-releases/version

cp -R capi-final-releases/* generated-release/*
