#!/bin/bash
set -e -x

source ~/.bashrc

# Shenanigans copied from to get MySQL running
# (Required because we generate our docs with rspec, and we've configured
#  our tests to require a database)
chmod 777 /tmp
service mysql restart

pushd cf-release/src/cloud_controller_ng
  chruby $(cat .ruby-version)

  gem install bundler
  bundle install

  # We don't care which database we use, but we don't want to bother starting postgres
  DB=mysql bundle exec rake spec:api

  aws s3 rm s3://cc-api-docs/release-candidate/ --recursive
  aws s3 cp doc/api s3://cc-api-docs/release-candidate --recursive

  # Generate documentation for http://v3-apidocs.cloudfoundry.org
  pushd docs
    bundle
  popd
  ./scripts/publish_docs_for_version.sh release-candidate
popd
