#!/usr/bin/env bash
set -e -x

service mysql restart
service postgresql restart

cd cloud_controller_ng

bundle install

bundle exec rake rubocop
DB=mysql bundle exec rake parallel:create
DB=postgres bundle exec rake parallel:create
bundle exec rake spec:all

