#!/usr/bin/env bash
set -e -x

source ~/.bashrc

if [ -n "$LOGS_DIR" ]; then
  mkdir $LOGS_DIR
fi

bosh -n --color -t $BOSH_DIRECTOR -d $DEPLOYMENT_YML $COMMAND
mv acceptance_tests*.tgz "bosh-logs/acceptance_tests-$(date '+%s').tgz"

