#!/usr/bin/env bash
set -e -x

echo "======ENVIRONMENT======"
printenv

pushd capi-release
  source .envrc

  go install github.com/onsi/ginkgo/ginkgo

  pushd src/github.com/cloudfoundry-incubator

    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race \
        cc-uploader nsync stager tps
  popd
popd