#!/usr/bin/env bash
set -e -x

: ${DB:?}

pushd cloud_controller_ng > /dev/null
  service mysql restart
  service postgresql restart
  if [ "${DB}" = "mssql" ]; then
    service docker restart
    ./scripts/run-ms-sql-background.sh
  fi

  bundle install

  bundle exec rake rubocop
  bundle exec rake spec:serial

  if [ "${DB}" = "mssql" ]; then
    ./scripts/stop-ms-sql-background.sh
  fi
popd > /dev/null
