#!/usr/bin/env bash

set -exu

function setup_env() {
  export AWS_DEFAULT_REGION
  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY
}

function check_stack() {
  local stack_name=$1

  aws cloudformation describe-stacks --stack-name "${stack_name}" 2>&1
}

function delete_stack() {
  local stack_name=$1

  aws cloudformation delete-stack --stack-name "${stack_name}"
}

function wait_for_stack() {
  declare stack_name=$1 timeout=$2 iterations status

  set +x
  iterations=0

  while true ; do
    iterations=$((iterations+1))

    if [ $iterations -gt $timeout ];then
      echo "Timed out waiting for stack to delete" >&2
      exit 1
    fi

    set +e
    status=$(check_stack "${stack_name}")
    set -e

    if echo "${status}" | grep -q DELETE_FAILED; then
      echo "Failed to delete stack!\n${status}" >&2
      exit 1
    fi

    if echo "${status}" | grep -q "does not exist"; then
      echo "Successfully deleted stack"
      exit 0
    fi

    echo -n . >&2
    sleep 1
  done
  set -x
}


function main() {
  setup_env
  delete_stack "${STACK_NAME}"
  wait_for_stack "${STACK_NAME}" 180
}

main
