#!/bin/bash

: "${pool_dir:="/${HOME:-/Users/pivotal}/workspace/capi-env-pool/bosh-lites"}"

function print_env_info {
  # Colors
  local red blue nc
  tty -s
  local is_interactive="$?"
  if [ "${is_interactive}" == "0" ]; then
    red='\033[0;31m'
    blue='\033[0;34m'
    nc='\033[0m'
  else
    red=''
    blue=''
    nc=''
  fi

  echo -e "${blue}Rounding up claimed environments...${nc}"

  pushd "${pool_dir}/claimed" > /dev/null
    stale_claimed_files="$(git log --reverse --name-only --pretty=format: --until="7 days ago" -- * | xargs)"
    fresh_claimed_files="$(git log --reverse --name-only --pretty=format: --after="7 days ago" -- * | xargs)"


    output="${blue}\n* ENV *\t* CLAIMED BY *\t* CLAIMED ON *\t* CLAIMED SINCE *\n"

    output="${output}${red}\n"
    for file in ${stale_claimed_files}; do
      file="$( basename "${file}" )"
      author="$(git log --pretty='format:%an' "${file}")"
      committer="$(git log --pretty='format:%cn' "${file}")"
      claimed_since="$(git log --pretty='format:%ar' "${file}")"
      workstation="$(git log --pretty='format:%s' "${file}" | sed -E "s/^manually claim [^[:space:]]+ on ([^[:space:]]+).*$/\1/")"

      if [ "${author}" != "${committer}" ]; then
        claimed_by="${author}+${committer}"
      else
        claimed_by="${author}"
      fi

        output="${output}${file}\t${claimed_by}\t${workstation}\t${claimed_since}\n"
    done

    output="${output}${nc}\n"

    for file in ${fresh_claimed_files}; do
      file="$( basename "${file}" )"
      author="$(git log --pretty='format:%an' "${file}")"
      committer="$(git log --pretty='format:%cn' "${file}")"
      claimed_since="$(git log --pretty='format:%ar' "${file}")"
      workstation="$(git log --pretty='format:%s' "${file}" | sed -E "s/^manually claim [^[:space:]]+ on ([^[:space:]]+).*$/\1/")"

      if [ "${author}" != "${committer}" ]; then
        claimed_by="${author}+${committer}"
      else
        claimed_by="${author}"
      fi

        output="${output}${file}\t${claimed_by}\t${workstation}\t${claimed_since}\n"
    done

  popd > /dev/null
  echo -e "$output" | column -t -s $'\t'
}

print_env_info
