#!/usr/bin/env bash

set -e

workspace_dir="$( pwd )"
updated_capi_ci_private="${workspace_dir}/updated-capi-ci-private"
output_path="${updated_capi_ci_private}/${ENVIRONMENT}"
delete_var_store_script="${workspace_dir}/capi-ci/ci/bbl-tasks/delete-var-store-certs.rb"

function delete_bbl_certs() {
  ${delete_var_store_script} ${output_path}/vars/director-vars-store.yml
  ${delete_var_store_script} ${output_path}/vars/jumpbox-vars-store.yml
}

function delete_cf_certs() {
  eval "$(bbl print-env)"
  # from the cf-deployment manifest, find all the certs by name,
  # then delete them from credhub one by one
  yq '.variables | .[] | select(.type=="certificate") | .name' <(bosh -dcf manifest) \
     |  xargs -n1 -I{} sh -c \
        "echo about to delete {} from credhub && credhub delete -n /bosh-${ENVIRONMENT}/cf/{}" \
     || true # best effort for reentrancy - we always want to bbl up even if this fails
}

function delete_bosh_dns_certs() {
  eval "$(bbl print-env)"

  bosh_dns_runtime_config_file="$(mktemp)"

  # Get bosh runtime config; we assume that bosh dns is deployed in this
  # runtime config. Pipe to `cat` to remove extra bosh cli output.  Remove
  # header from bosh cli output, trim any tab characters and format to yaml. Whew.
  bosh -d cf config --type runtime --name dns | cat | tail +5 | tr -d '\t' | yq -y . > "$bosh_dns_runtime_config_file"

  yq '.variables | .[] | select(.type=="certificate") | .name' "$bosh_dns_runtime_config_file" \
     |  xargs -n1 -I{} sh -c \
        "echo about to delete {} from credhub && credhub delete -n {}" \
     || true # best effort for reentrancy - we always want to bbl up even if this fails
}

function commit_capi_ci_private() {
  if [[ -n $(git status --porcelain) ]]; then
    git config user.name "CI Bot"
    git config user.email "cf-capi-eng@pivotal.io"

    git add "${updated_capi_ci_private}/${ENVIRONMENT}"
    git commit -m "Initial commit for '${ENVIRONMENT}'"
  fi
}

cp -rf capi-ci-private/. ${updated_capi_ci_private}

mkdir -p "${updated_capi_ci_private}/${ENVIRONMENT}"
pushd "${updated_capi_ci_private}/${ENVIRONMENT}"
  delete_cf_certs
  delete_bosh_dns_certs

  if [ "$1" != "cf-only" ]; then
    delete_bbl_certs
  fi

  commit_capi_ci_private
popd
