#!/usr/bin/env bash
set -e

echo "======ENVIRONMENT======"
printenv

service postgresql start

pushd cc-uploader
  CC_UPLOADER_SHA=$(git rev-parse HEAD)
popd

pushd nsync
  NSYNC_SHA=$(git rev-parse HEAD)
popd

pushd stager
  STAGER_SHA=$(git rev-parse HEAD)
popd

pushd tps
  TPS_SHA=$(git rev-parse HEAD)
popd

pushd capi-release
  source .envrc

  go install github.com/onsi/ginkgo/ginkgo

  pushd src/code.cloudfoundry.org
    pushd cc-uploader
      git fetch
      git checkout "${CC_UPLOADER_SHA}"
    popd

    pushd nsync
      git fetch
      git checkout "${NSYNC_SHA}"
    popd

    pushd stager
      git fetch
      git checkout "${STAGER_SHA}"
    popd

    pushd tps
      git fetch
      git checkout "${TPS_SHA}"
    popd

    ginkgo -r -keepGoing -p -trace -randomizeAllSpecs -progress --race \
        cc-uploader nsync stager tps
  popd
popd
