#!/usr/bin/env bash
set -e

: ${DB:?}

pushd cloud_controller_ng > /dev/null
  service mysql restart
  service postgresql restart
  if [ "${DB}" = "mssql" ]; then
    service docker start
    trap 'service docker stop' EXIT
    sleep 5

    LOG_FILE="/tmp/mssql.log" ./scripts/run-ms-sql-background.sh
  fi

  bundle install

  bundle exec rake rubocop
  bundle exec rake spec:serial
popd > /dev/null
