resources:
- name: concourse-cve-scan
  type: git
  source:
    uri: https://github.com/cloudfoundry-incubator/concourse-cve-scan.git
    branch: main
- name: capi-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/capi-release.git
jobs:
- name: check-for-cves
  plan:
  - in_parallel:
      - get: concourse-cve-scan
      - get: capi-release-develop
        trigger: true
  - task: scan-with-syft-and-grype
    input_mapping:
      bosh-release-repo: capi-release-develop
    file: concourse-cve-scan/tasks/scan-for-cves/scan-for-cves.yml
    params:
      GRYPE_FAILURE_LEVEL: critical